# ==============================================================================
# KIBANA CONFIGURATION
# ==============================================================================
# Configuration for Kibana dashboard.
# ==============================================================================

# ------------------------------------------------------------------------------
# SERVER CONFIG
# ------------------------------------------------------------------------------
server.name: kibana
server.host: "0.0.0.0"

# ------------------------------------------------------------------------------
# ELASTICSEARCH CONNECTION
# ------------------------------------------------------------------------------
elasticsearch.hosts: ["http://elasticsearch:9200"]

# ------------------------------------------------------------------------------
# MONITORING
# ------------------------------------------------------------------------------
monitoring.ui.container.elasticsearch.enabled: true
